### ISSUE TITLE
US 02.01.01 - Add Photo with Geolocation go QR codes

### ISSUE THREAD

**Issue by AyanB123** [CMPUT301W23T41/SnailsCurlUp#12]
US 02.01.01 
As a player, I want to be able to scan QR codes and record a photo of the location or object, and the geolocation of the location or object.
Story Points: M (3)
Risk Level: Medium

**Comment by Zgell** [comment]
Just cleaning up old issues that have been technically solved. This one has been done for a while now ever since @MAl-l3R 's scan code got merged into master.
