### ISSUE TITLE
US 01.04.01- see highest and lowest QRcode

### ISSUE THREAD

**Issue by lawrence080** [CMPUT301W23T41/SnailsCurlUp#17]
As a player, I want to see my highest and lowest scoring QR codes.

**Comment by JKHellNo** [comment]
If you have the gallery set, (grid view), i can just make the query for you.

**Comment by Zgell** [comment]
This is currently functional inside of the `QrCodeFunc` branch, just waiting for that branch to be complete to mark this as done.

**Comment by Zgell** [comment]
I believe this is now in master as part of the sorting feature on the profile page.
