### ISSUE TITLE
US 07.01.01 - Game-Wide High Scores

### ISSUE THREAD

**Issue by Zgell** [CMPUT301W23T41/SnailsCurlUp#18]
US 07.01.01

As a player, I want to see game-wide high scores of all players.

**Story Points**: L (5)

**Risk Level**: Medium

**Comment by Zgell** [comment]
This makes me think that we should probably consider whether or not we want to include the cumulative score of a player in the database. If we don't, it could make computing the leaderboard very difficult as it would require the leaderboard to search across all users and compute all of their total scores at query time, which means that it searches across all users AND all QRInstances. We should discuss this further at our next meeting.

**Comment by JKHellNo** [comment]
The current database in firebase is designed the way it is right now with "total score" data field exactly for that reason.
