### ISSUE TITLE
US 01.05.01 - see the sum of scores have scaned

### ISSUE THREAD

**Issue by lawrence080** [CMPUT301W23T41/SnailsCurlUp#19]
As a player, I want to see the sum of scores of QR codes that I have scanned.

**Comment by Zgell** [comment]
This should be a simple fix, I can take this on later (maybe tonight, maybe tomorrow).

**Comment by Zgell** [comment]
Currently functional inside of the `QrCodeFunc` branch, will be marked as done when it is merged in.

**Comment by Zgell** [comment]
This is now in master as part of Ayan's rework of the user profile UI.
