### ISSUE TITLE
US 04.01.01  a profile with a unique username and contact information.

### ISSUE THREAD

**Issue by GordonGu1900** [CMPUT301W23T41/SnailsCurlUp#21]
US 04.01.01

As a player, I want a profile with a unique username and my contact information.

Story Points: S (2)

Risk Level: Medium

**Comment by Zgell** [comment]
This is now technically satisfied with the addition of @AyanB123 's partial user profile, so I'm going to mark this off for now. As with a small handful of other user stories, some improvements should be made before Part 4.

**Comment by AyanB123** [comment]
Have partial implementation for now
