### ISSUE TITLE
US 02.02.01 - Add Comments to QR codes.

### ISSUE THREAD

**Issue by AyanB123** [CMPUT301W23T41/SnailsCurlUp#23]
US 02.02.01
As a player, I want to be able to comment on QR codes.
Story Points: XS(1)
Risk Level: Low

**Comment by MAl-l3R** [comment]
I can do this. Just have to add a EditText view for Comment in Decode fragment.

**Comment by AyanB123** [comment]
I have implemented most of it just have small tweaks left

**Comment by Zgell** [comment]
This is done, more or less. Aside from a minor bug that means that comments may or may not be synced in the DB, the client-side implementation is done.
