### ISSUE TITLE
US 02.03.01 - Browse QR codes other player scanned

### ISSUE THREAD

**Issue by AyanB123** [CMPUT301W23T41/SnailsCurlUp#29]
US 02.03.01
As a player, I want to be able to browse QR codes that other players have scanned.
Story Points: L(5)
Risk Level: Medium

**Comment by Zgell** [comment]
I know we had plans for a dedicated gallery but this is *debatably* solved with the addition of searching for QR codes. That lets you browse user profiles, which consequently lets you browse QR codes as well.

**Comment by Zgell** [comment]
Update: Since Lawrence's branch has been merged in, I'm closing this issue because this is technically satisfied (even if the specific implementation leaves us a little *unsatisfied*).
