### ISSUE TITLE
Figure out Hashing Algorithm for QR Codes

### ISSUE THREAD

**Issue by Zgell** [CMPUT301W23T41/SnailsCurlUp#34]
When it comes to not storing the QR code images themselves on the server or in the application, the logical conclusion is that we should use some kind of hashing algorithm (ie. SHA256) to compute the hash of the QR code. We need to determine which hashing algorithm we will use for hashing the QR codes, as well as come up with how we'll interpret the hash for determining the name/appearance of the QR code (all of which are auto-generated by the hash).

Objectives:

- [x] Determine which hashing algorithm to use.
- [x] Figure out how to use the algorithm in Java (ie. Java standard library, third-party library)
- [x] Figure out how to interpret the algorithm for human-readable names/appearance
  - How many different combinations do we want?
  - What parts of the hash should control what parts of the name/appearance?

Stories this is related to:
- #13 
- #30 
- #31

**Comment by MAl-l3R** [comment]
Completed this a while ago
