### ISSUE TITLE
Set up Firebase Database

### ISSUE THREAD

**Issue by Zgell** [CMPUT301W23T41/SnailsCurlUp#35]
We'll all need access to a Firebase database in order to get most inter-user functionality in the app working.

Objectives:

- [x] Create a new Firebase database.
- [x] Make sure all team members have access to the database.
- [x] Connect the database to the project.

**Comment by Zgell** [comment]
I'm going to tentatively assign this one to myself, but it may get moved around. This one is kind of tricky and easy to mess up, so ideally I would handle it so that you guys don't have to mess with this stuff.

**Comment by JKHellNo** [comment]
Google.json file is manually shared and implemented. All members have access to the database and the project can connect  to the database.
