### ISSUE TITLE
Find out how to access Uniquely-Identifiable Device Information

### ISSUE THREAD

**Issue by Zgell** [CMPUT301W23T41/SnailsCurlUp#36]
Objectives:

- [ ] Find out what kinds of device information can be obtained by Java/Android Studio during a program's runtime (will involve a little bit of research)
- [ ] Figure out what piece of information would be best to uniquely identify a device (ie. some kind of hardware address)
- [ ] Figure out how to use this device ID (ie. some kind of hash) for the login system (you are not required to actually implement this yet)

Related Issues:
- #24

**Comment by JKHellNo** [comment]
Ayan solved the "login using device" by implementing collectionPreferences. The user device stores the information and can hence "log into my application without using a username and password as my device can identify me." You can refer to what i've said within the particular relevant issue.
