### ISSUE TITLE
QR Code Position Discrepancy

### ISSUE THREAD

**Issue by Zgell** [CMPUT301W23T41/SnailsCurlUp#45]
Less of a bug, more of a design issue with how we currently have QR codes implemented. Currently, a "QR Code" object stores the data of a QR code (from which name, score, and picture can be derived) and the geolocation it was discovered at (if geolocation supplied). However, there are some concerns with the way we handle more than one instance of a QR code that has the same data but different geolocation values.

Currently, the QR codes collection in the database assumes that there will be at most one instance of a QR code in the database. However this may not always be true, so we need to find a good way to reconcile multiple geolocational positions for the same QR code.

**Comment by Zgell** [comment]
Update on this issue: as a result of the March 16th meeting, we now have a restructuring of the QR codes underway to make sure this problem is resolved. We're splitting the idea of a "QR Code" into three distinct groups: a "QRInstance" which represents a specific QR code owned by one user, a "MapMarker" which represents a real-world QR code with a location to be plotted on the map, and an "AbstractQR" which represents all QR codes of a certain type (ie. all QR codes named "Fuzzy"). This new structure was intended to solve a lot of issues with efficiently searching in the database for values but solves this issue as a consequence.

**Comment by Zgell** [comment]
@AyanB123 I'm assigning you to this issue since you're the one handling the changes to the QR code classes as we discussed last meeting.

**Comment by AyanB123** [comment]
Okay perfect thanks a lot have delt with most of it, still sorting out specific of implementing the MapMarker Part but other area have been completed

**Comment by Zgell** [comment]
I believe this is now dealt with following some of the changes we've made to the "QR Instance vs. Abstract QR" dichotomy.
