### ISSUE TITLE
Fix the Login Page

### ISSUE THREAD

**Issue by Zgell** [CMPUT301W23T41/SnailsCurlUp#52]
Currently the "Login" page is not exactly functional for reasons I don't understand. The "Log in" button that should be under the username text box does not appear, and so users cannot proceed to log in.

**Comment by MAl-l3R** [comment]
there also seems to be issues with ui design. The layout looks weird in my device, so we might have to make the layout more relative so it fits nicely in devices of all sizes.

**Comment by Zgell** [comment]
Definitely need to fix that. UI is a bit inconsistent and definitely problematic. Might be worth looking into converting certain layouts into constrained layouts so everything is responsive and works on many other devices.

**Comment by GordonGu1900** [comment]
Yes the UI mismatch to the screen is affecting intent test.

**Comment by lawrence080** [comment]
the scale of the hole page seems bugging out. The button under text area is not showing properly on my end.

**Comment by Zgell** [comment]
@MAl-l3R correct me if I'm wrong but you're the one working on this for now, correct? Assigning it to you in GitHub for now but feel free to re-assign it if I am wrong.

**Comment by MAl-l3R** [comment]
yes correct
