### ISSUE TITLE
US 01.01.01 - Add QRs to Account

### ISSUE THREAD

**Issue by Zgell** [CMPUT301W23T41/SnailsCurlUp#8]
US 01.01.01

As a player, I want to add new QR codes to my account.

**Story Points**: XS (1)

**Risk Level**: Low

**Comment by JKHellNo** [comment]
QR's can be added to user's QR wallet in the firebase

**Comment by Zgell** [comment]
Technically complete now, although further testing is required to make sure that there is proper synchronization between the local data stored in the app and the database data.

**Comment by AyanB123** [comment]
still need to synchronize it for next part so works better, recommend we setup alll conection and syncing from database fully
